# /docker-compose.yaml
version: "3.9"

services:
  next:
    build:
      context: ./packages/next
      dockerfile: Dockerfile
    volumes:
      - ./packages/next:/app
    ports:
      - 3000:3000
    command: npm run dev

  postgres:
      image: postgres:13
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=mydb
      networks: [ pg ]
      volumes:
          - ./data/pg:/var/lib/postgresql/data

networks:
    pg: